### ISSUE TITLE
write after end: internal error

### ISSUE THREAD

**Issue by charlierudolph** [arturadib/shelljs#206]
Unsure whats going on here. Redacted some of the paths but the gist is I was just running a simple git command with `exec` and this error occurs inconsistently.

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at WriteStream.Writable.write (_stream_writable.js:214:5)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)
shell.js: internal error
Error: Command failed: "/usr/local/Cellar/node/0.12.2_1/bin/node" /var/folders/tc/3nj4rdm51sd47dd9smfx8jwr0000gn/T/shelljs_81b3df4c8d0f8dddc564
  at checkExecSyncError (child_process.js:1346:13)
  at Object.execSync (child_process.js:1386:13)
  at execSync (/.../shelljs/src/exec.js:77:11)
  at Object._exec (/.../shelljs/src/exec.js:210:12)
  at Object.exec (/.../shelljs/src/common.js:182:23)
```

**Comment by pwang2** [comment]
+1

**Comment by pwang2** [comment]
Just in case we are doing something quite similar on jenkins.  if you do shelljs.exec('git checkout branchname') when you are already in that branch, you will get this error.

**Comment by dmccer** [comment]
+1

**Comment by manovotny** [comment]
I hit this exact same issue today trying to use `exec` to run `git checkout gh-pages`. 

I tried to dig into shelljs, but all the further I got is that [it seems to be failing on the `common.state` of `tempdir.js`](https://github.com/arturadib/shelljs/blob/master/src/tempdir.js#L36). Once I try to step overt that line, it just bombs. Which is weird as it's just checking the `state` object in `common.js`. 

Here's my stack, in case it helps for anything.

```
Switched to a new branch 'gh-pages'
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at WriteStream.Writable.write (_stream_writable.js:214:5)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:529:20)
shell.js: internal error
Error: Command failed: "/usr/local/Cellar/node/0.12.0/bin/node" /var/folders/bf/3ngjk63s3f5_6chlm9mpgny5drfny6/T/shelljs_0bab9ffb523df5123cf6
    at checkExecSyncError (child_process.js:1339:13)
    at Object.execSync (child_process.js:1379:13)
    at execSync (/Users/mn42754/Developer/Repositories/deere-ui/gh-pages-deploy/node_modules/shelljs/src/exec.js:77:11)
    at Object._exec (/Users/mn42754/Developer/Repositories/deere-ui/gh-pages-deploy/node_modules/shelljs/src/exec.js:210:12)
    at Object.exports.wrap [as exec] (/Users/mn42754/Developer/Repositories/deere-ui/gh-pages-deploy/node_modules/shelljs/src/common.js:182:23)
    at Object.checkoutGitHubPagesBranch (/Users/mn42754/Developer/Repositories/deere-ui/gh-pages-deploy/bin/github.js:7:11)
    at Object.<anonymous> (/Users/mn42754/Developer/Repositories/deere-ui/gh-pages-deploy/bin/cli.js:20:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

Here is the temp file, `shelljs_0bab9ffb523df5123cf6`, that shelljs created for this process too, if that helps.

```
var child = require('child_process')
  , fs = require('fs');
var childProcess = child.exec('git checkout gh-pages', {env: process.env, maxBuffer: 20*1024*1024}, function(err) {
  fs.writeFileSync('/var/folders/bf/3ngjk63s3f5_6chlm9mpgny5drfny6/T/shelljs_0837e612d0d002ab6c39', err ? err.code.toString() : '0');
});
var stdoutStream = fs.createWriteStream('/var/folders/bf/3ngjk63s3f5_6chlm9mpgny5drfny6/T/shelljs_65ab653ee72bff94bc23');
childProcess.stdout.pipe(stdoutStream);
childProcess.stderr.pipe(stdoutStream);
childProcess.stdout.pipe(process.stdout);
childProcess.stderr.pipe(process.stderr);
```

And the resulting output file, `shelljs_65ab653ee72bff94bc23`, mentioned in the file above.

```
Switched to a new branch 'gh-pages'
```

And... Now that I look at it, the `shelljs_0bab9ffb523df5123cf61` file above mentions `shelljs_0837e612d0d002ab6c39` in this line of code...

```
fs.writeFileSync('/var/folders/bf/3ngjk63s3f5_6chlm9mpgny5drfny6/T/shelljs_0837e612d0d002ab6c39', err ? err.code.toString() : '0');
```

...but I don't see the `shelljs_0837e612d0d002ab6c39` it references on my file system. Could that be the write it's failing on?

What's also weird is that it actually does checkout my `gh-pages` branch and successfully switches to it. So, it's like the command succeeded, but something in shelljs choked.

**Comment by manovotny** [comment]
A couple of updates...

* Unlike @pwang2, I was not already on the branch. I was simply trying to check it out locally for the very first time.
- When I reported the issue, I was using version `0.5.1`. I tried downgrading to `0.5.0`, but the issue persisted. Downgrading to `0.3.0` seems to make the issue go away and the script runs successfully.

Hopefully that helps isolate the issue some more.

**Comment by pwang2** [comment]
you could just use shjs CLI to run your shelljs_0bab9ffb523df5123cf6 file.  The case here is more node childprocess io pipe.  Here is the result for my case. 
```javascript
var child = require('child_process')
  , fs = require('fs');
var childProcess = child.exec('git checkout develop', {env: process.env, maxBuffer: 20*1024*1024}, function(err) {
  console.log('done');
  fs.writeFileSync('/var/folders/9s/3y2vm83n1ng8svlgfnvq618n74grbf/T/shelljs_79ae30d948604321e17d', err ? err.code.toString() : '0');
});
console.log('done2');
var stdoutStream = fs.createWriteStream('/var/folders/9s/3y2vm83n1ng8svlgfnvq618n74grbf/T/shelljs_9db3c6e84b590d9e5c0c');
childProcess.stdout.pipe(stdoutStream);
childProcess.stderr.pipe(stdoutStream);

console.log('done3');
childProcess.stdout.pipe(process.stdout);

console.log('done4');
childProcess.stderr.pipe(process.stderr);
console.log('done5');
```

git:(develop) ✗  **node** /var/folders/9s/3y2vm83n1ng8svlgfnvq618n74grbf/T/shelljs_71a1b17f63dfdbdc7568
done2
done3
done4
done5
Already on 'develop'
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at WriteStream.Writable.write (_stream_writable.js:214:5)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)

The error happened in `child_process.exec('git checkout develop',cb)`. if you run 
```javascript
require('child_process').exec('git checkout develop',function(err,stdout,stderr){console.log(err,stdout,stderr)})
```
you get  
 null 'Your branch is up-to-date with \'origin/develop\'.\n' 'Already on \'develop\'\n'

So the case here is, node run the file and close the file handler, when child process return anything, default stdout and stderror has been closed.  If you move all done2,3,4,5 in the cb it will work well. 

shelljs is kinda buggy for exec, in our case it should not use async as per document.

>exec(command [, options] [, callback])
>Available options (all false by default):
>async: Asynchronous execution. Defaults to true if a callback is provided.
>silent: Do not echo program output to console.

**Comment by pwang2** [comment]
so, NOT only checkout current branch will get this. My apologies.

**Comment by ArielAbreu** [comment]
+1 I get this by running `exec('unzip blah.zip -d folder')`.
